#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network AND read mac address form eeprom: "

	# Read proper mac address from eeprom
	read_mac=$(/scripts/at24mac)
	change_mac=$(macchanger -m ${read_mac} eth0)
	printf "%s\n" "$read_mac"
	printf "%s\n" "$change_mac"

	/sbin/ifup -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

